import { Inter } from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';
import SessionWrapper from '@/components/sessionWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Afro AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang='en'>
        <body className={`${inter.className}bg-black`}>{children}</body>
      </html>
    </SessionWrapper>
  );
}
