'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/sharedComponents/Navbar';
import Footer from '@/components/sharedComponents/Footer';
import Hero from '@/components/homeComponents/Hero';
import Partners from '@/components/homeComponents/Partners';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='favicon.ico' />
        <title>AfroAI</title>
      </head>
      <body className={`${inter.className}bg-black`}>
        <Navbar />
        <section className='bg-inherit '>{children}</section>
        <Footer />
      </body>
    </html>
  );
}
